### ISSUE TITLE
No module named 'officialresnet'

### ISSUE THREAD

**Issue by pouya1991** [google-research/rigl#1]
Hi,
I am trying to run imagenet_train_eval.py but I get the following error:
`Traceback (most recent call last):
  File "rigl/imagenet_resnet/imagenet_train_eval.py", line 37, in <module>
    from officialresnet import imagenet_input
ModuleNotFoundError: No module named 'officialresnet'
`
Should I install officialresnet library separately?
Thanks

**Comment by evcu** [comment]
Hi, 

Thanks for pointing this out. We are using the input-pipeline from https://github.com/tensorflow/tpu/tree/master/models/official/resnet. 

So a short solution would be to clone this repo and add models/ to the python path.  Then the import should be `from offical.resnet import imagenet_input`. 

I will fix the type and add explanation to the README.md, soon.

**Comment by evcu** [comment]
just updated the code. Please, let us know if you face any other issues.
