### ISSUE TITLE
RigL TF2 - Initial Sparsification

### ISSUE THREAD

**Issue by AmoghDabholkar** [google-research/rigl#11]
There is an on-going effort to open-source a tf2 version with tf-model_optimization toolkit. It should be out in few months. Pytorch implementation is on hold (I plan to do when I have more time), but I am happy to help if you are interested adding that to the repo.

_Originally posted by @evcu in https://github.com/google-research/rigl/issues/2#issuecomment-697203559_

Hello @evcu ,
I am going through the TF2 implementation for RigL and I'm trying to understand how the initial sparsification of the model is being controlled? I don't see an explicit argument for mask_init_method like in the TF1 implementation which I can set to as ERK or uniform. Can you point me to how I can control the initial sparsification of the model? Is it through pruning_params in rigl.gin config file?

**Comment by evcu** [comment]
This is easy to do, but as you rightly say it is not used in current code. Currently I'm on holiday, but will share instructions for this in June when I'm back.

**Comment by AmoghDabholkar** [comment]
Thanks @evcu 
That will be very helpful!

**Comment by evcu** [comment]
This can be done using something like this:
```python
for layer in head.layers: 
  if not isinstance(layer, pruning_wrapper.PruneLowMagnitude): 
     continue mask = layer.pruning_vars[0][1]
     rigl.sparse_utils.get_mask_init_fn([mask], init_method, sparsity, {})
```
