### ISSUE TITLE
Using Rigl to train with structured sparsity

### ISSUE THREAD

**Issue by abhishektyaagi** [google-research/rigl#15]
Hi,
Thank you for sharing your work.

I have been using this  codebase by modifying the initial sparsification method to give some structured sparsity to the network. Now, what I would like is to make sure that when back-propagation takes place and weights are updated, they only update the values in the initial non-zero positions and do not update the positions which are already zero.

How can I achieve this with the codebase here?

**Comment by evcu** [comment]
It has been a while since I looked at the code here.  I would recommend using [jaxpruner ](https://github.com/google-research/jaxpruner). There you can easily set-up a custom mask at initialization.
