### ISSUE TITLE
Hello, can I use this method to sparse my own neural network?

### ISSUE THREAD

**Issue by H-Wenfeng** [google-research/rigl#2]
Hello, can I use this method to sparse my own neural network?
Your work is so cool！

**Comment by evcu** [comment]
Sure, it should be easy to do if it is tensorflow-v1. We are planning to open-source tf2 and pytorch versions, soon.

**Comment by gupta-abhay** [comment]
hello, thanks for this implementation - just wondering when you plan to open source the pytorch / tf2 versions of this?

**Comment by evcu** [comment]
There is an on-going effort to open-source a tf2 version with tf-model_optimization toolkit. It should be out in few months. Pytorch implementation is on hold (I plan to do when I have more time), but I am happy to help if you are interested adding that to the repo.

**Comment by AmoghDabholkar** [comment]
Hello @evcu 
I am going through the TF2 implementation for RigL and I'm trying to understand how the initial sparsification of the model is being controlled? I don't see an explicit argument for mask_init_method like in the TF1 implementation which I can set to as ERK or uniform. Can you point me to how I can control the initial sparsification of the model? Is it through pruning_params in rigl.gin config file?
