### ISSUE TITLE
Question: what is the speed up gain from Rigl and other methods implemented here in training?

### ISSUE THREAD

**Issue by ofirzaf** [google-research/rigl#3]
Hi,

I wonder if the code implementation for Rigl (and other methods like SET) here shows real speed up gain and less memory consumption when training compared to training a dense model or does it only simulate the method in terms of accuracy?

Thanks,
Ofir

**Comment by evcu** [comment]
Our implementation is using masking, so it is simulating. Check-out graphcore's implementation for efficient training (see README.md).
