### ISSUE TITLE
Specify TF and TF.data versions?

### ISSUE THREAD

**Issue by varun19299** [google-research/rigl#4]
Hi,

I tried running the `cifar10` example with:

```
tensorflow-datasets      1.3.0
tensorflow-estimator     1.15.1
tensorflow-gpu           1.15.4
```

This fails with the error:

```
  File "/srv/home/varunsundar/rigl/rigl/cifar_resnet/data_helper.py", line 105, in input_fn
    images_batch, labels_batch = tf.compat.v1.data.make_one_shot_iterator(
  File "/srv/home/varunsundar/.conda/envs/tf37/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1'
``` 

Seems like the tensor flow version is too high (too new)- I'm guessing `tf.compat.v1.data` became `tf.data`?

Could you specify the exact tf and tf-datasets versions to be used for reproduction?

**Comment by evcu** [comment]
Thanks for noticing the bug; `compat.v1` is extra. I will send some CLs to fix it and I will add tensorflow-datasets version, too

**Comment by evcu** [comment]
Latest fix should fix the issue: https://github.com/google-research/rigl/commit/989790111c304601a364f846ea198b42208781d9
