### ISSUE TITLE
How to train own convolutional network

### ISSUE THREAD

**Issue by zebraForever** [google-research/rigl#6]
Hi, good work!
How can I train my CNN using RIGL?

In issue #2 , you recommend modify the model and wrap the optimizer but no matter how I try to do it, for my CNN it doesn't work.

Can you tell me exactly how this is done for CNN?

Thank you!

**Comment by evcu** [comment]
Thanks for reaching out

Well there are 2 different training that trains CNNs (cifar, imagenet). What do you mean it doesn't work? Is it the code or the algorithm. For the later there could be many reasons. Regardless happy to help; is your code public?

Best

**Comment by zebraForever** [comment]
Unfortunately my code is not publicly available.

The thing is, I am replacing the model from mnist_train_eval.py with my own CNN model.When I run the script, I don't get the desired result.
Should I try replacing the model in cifar, imagenet or is it better to write my own implementation for my model?
