### ISSUE TITLE
Can you post the CIFAR-10 results of the paper?

### ISSUE THREAD

**Issue by ofirzaf** [google-research/rigl#8]
Hi,

I am trying to reproduce your paper's results on CIFAR-10 in PyTorch. In the paper figure 4 describes the results however there are no exact numbers.
Can you please post the exact results you got from your experiments on CIFAR?

Thanks

**Comment by evcu** [comment]
It would be great to have your pytorch implementation referenced in the README.md. Let me know if you have any further questions. 

Best

RigL (ERK)
Sparsity: 0.5, Acc: 0.942
Sparsity: 0.8, Acc: 0.936
Sparsity: 0.9, Acc: 0.929
Sparsity: 0.95, Acc: 0.918

RigL$_{2\times}$ (ERK)
Sparsity: 0.5, Acc: 0.942
Sparsity: 0.8, Acc: 0.938
Sparsity: 0.9, Acc: 0.933
Sparsity: 0.95, Acc: 0.924

Static (ERK)
Sparsity: 0.5, Acc: 0.941
Sparsity: 0.8, Acc: 0.929
Sparsity: 0.9, Acc: 0.915
Sparsity: 0.95, Acc: 0.890

Static$_{2\times}$ (ERK)
Sparsity: 0.5, Acc: 0.941
Sparsity: 0.8, Acc: 0.932
Sparsity: 0.9, Acc: 0.918
Sparsity: 0.95, Acc: 0.897

Pruning (ERK)
Sparsity: 0.5, Acc: 0.940
Sparsity: 0.8, Acc: 0.936
Sparsity: 0.9, Acc: 0.933
Sparsity: 0.95, Acc: 0.923
