### ISSUE TITLE
MetaInit w. VGG

### ISSUE THREAD

**Issue by sonnguyentruong129** [google-research/rigl#9]
I want to try MetaInit with VGG. Can you share some instructions for it? Thank you so much

**Comment by evcu** [comment]
I dont think we have this in the codebase. We once tried on mnist using the tf2 implementation and didnt get good results. I recommend using the tf-2 if you want to try yourself. But you need to implement both meta init and vgg. Or, You have to hack the tf-1 code for meta-init.
